name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # セルフホストランナーで動作させるための設定
    runs-on: self-hosted
    steps:

    # リポジトリをチェックアウト
    - uses: actions/checkout@v2

    # リポジトリのルートディレクトリに設置された`test.bat`ファイルを`foo`, `bar`という引数で実行
    - name: Run a bat file with arguments
      run: ./test.bat foo bar
    
    # 環境変数を設定する場合
    - name: Run a bat file with arguments and env
      run: ./test.bat foo bar
      env:
        FOO_ENV: bar

    - name: deploy
      run: echo deploy command here
